### ISSUE TITLE
Clarification for input with "invalid" list attribute

### ISSUE THREAD

**Issue by eps1lon** [w3c/html-aria#194]
As far as I can tell the spec does not constrain what kind of values the `list` attribute of a `<input type="text" />` should have in order to be recognized as a `combobox`.

However, it seems like that some implementations do apply constrains. The chrome accessibility view as well as nvda 2019.2 (chrome 78 and edge 18) do not announce a `<input type="text" list="non-existing-id" />` as a `combobox`. 

Does the "with a [...] attribute" imply that the attribute in question has to be valid? If so should this be added to each row or is a single note before the table sufficient?

**Comment by scottaohara** [comment]
@eps1lon, It's invalid HTML to have a `list` attribute without a value, or with an invalid value (e.g. `id` that doesn't exist in the document).  

I suppose we could add a "with a **valid** list attribute" to the row that indicates when the form controls would be considered a `role=combobox`.  However, I am not convinced that this spec even needs to mention that, since it isn't the purpose of this specification to indicate what you're asking about, but rather to indicate valid use of ARIA with HTML elements.

**Comment by eps1lon** [comment]
@scottaohara Makes sense to imply valid html. Thank your for the clarification!
