### ISSUE TITLE
Allow aria-invalid on more elements

### ISSUE THREAD

**Issue by jnurthen** [w3c/html-aria#20]
The whole point of aria-invalid is to allow authors to specify that elements are not valid to accessibility APIs. The ARIA in HTML document seems to disallow this usage. 

Custom validation logic often requires things that we either cannot do in HTML5, or where browser behaviour in HTML5 is not consistent. UX designers often require consistent behaviour across browsers.

**Comment by stevefaulkner** [comment]
@jnurthen have updated the restriction:

"The aria-invalid attribute for may be used on any HTML5 elements that allow global aria-\* attributes except submittable elements that have the required attribute set."

the restriction on submittable elements with the required attribute is there because when present the required attribute sets the invalid state.
