### ISSUE TITLE
link element inconsistent between html-aria and html-aam

### ISSUE THREAD

**Issue by carmacleod** [w3c/html-aria#205]
[HTML-ARIA for `link` element](https://w3c.github.io/html-aria/#el-link) says:
> `link` element with a `href` | `role=link` | No `role` or `aria-*` attributes

- Maps link with href to role link.
- Doesn't mention any mapping for link with no href.

----
[HTML-AAM for `link` element](https://w3c.github.io/html-aam/#el-link) says:
> No corresponding role | Not mapped | ...

- Maps link to no role, regardless of whether or not there's an href.

----
Not sure what the correct mappings should be in either spec; just pointing out an inconsistency.

**Comment by JAWS-test** [comment]
That's all right, because one is the a element (with href equal to role=link, specified the same in both documents), the other is the link element (so no link)

**Comment by JAWS-test** [comment]
[HTML spec](https://html.spec.whatwg.org/multipage/semantics.html#the-link-element) says

>    Two categories of links can be created using the link element: Links to external resources and [hyperlinks](https://html.spec.whatwg.org/multipage/links.html#hyperlink). The [link types section](https://html.spec.whatwg.org/multipage/links.html#linkTypes) defines whether a particular link type is an external resource or a hyperlink. ...  If the rel attribute is absent, has no keywords, or if none of the keywords used are allowed according to the definitions in this specification, then the element does not create any links. 

So the role does not depend on the href, but on the value in rel.

But: Since the link element is not rendered by the browser and does not exist in the accessibility tree, there should be no mapping.

The links are applied to the entire page and can be displayed as navigation targets by the browser (probably via the menu). But we don't need any mapping, because the links are never displayed within the HTML page.

**Comment by scottaohara** [comment]
The `link` element may be used in the `body` of a document if it has a body-ok `rel`.  With CSS, one can get the link to be visually displayed, and by adding a `tabindex=0`, it can be keyboard focusable - https://codepen.io/scottohara/pen/bGNgoGL  (note: the markup of this codepen passes the HTML validator)

The demo in the codepen likely will not be announced as having any content with IE11, as I'm using CSS pseudo content to inject the text "what a bad idea", and if memory serves, CSS content is not properly exposed by IE11.

Quickly testing the linked codepen with Apple's a11y inspector, the `link` has a platform exposed role of `AXLink`, *if* it has an `href` attribute.  If the `href` is removed, it is exposed as an `AXGroup`.  

Adding or removing the `rel` has no impact on whether it's exposed as a `AXLink` or not, but without a valid `rel` with body-ok value, it does become invalid as far as what's allowed by the HTML specification.

So, with all that said, if we were to update _anything_ with ARIA in HTML, it would be to say `link` has no corresponding role if it does not have an `href`.  If someone wants to make a PR to add in that information, I'd accept it...but I think it's pretty low priority, as with or without `href`, a `link` should still not be allowed to have any ARIA attributes applied to it.  

What I think this issue has helped uncover is that HTML AAM *does* need to be updated to record platform mappings for the `link` element (likely just resulting in `link`'s mappings pointing to `role=link`).  However, we'd also likely want to have a comment there explaining that typically `link` is not a user-facing element.

**Comment by JAWS-test** [comment]
The trick of making an invisible element visible also works with other invisible elements such as style, script, and template. But it doesn't change the fact that a link element is usually invisible and doesn't exist in the accessibility tree.

**Comment by scottaohara** [comment]
i'm not disputing that fact, so i'm not sure why you're responding as if i am.  

What i am noting is that `link` does has a platform mapping if exposed, and that mapping is tied to if the `href` is present on the element, and not the `rel`.  

Again, per the purposes of _this_ specification, it's largely irrelevant because it doesn't change the fact that, even if exposed developers should not use ARIA on `link` elements.

However, for the purposes of HTML AAM, the mappings are presently inaccurate as the element _does_ have a mapping, even though its default state is for it to not be exposed to the accessibility api.

**Comment by scottaohara** [comment]
i'm not disputing that fact...  

What i am stating is `link` *does* has a platform mapping *if exposed*, and that mapping is tied to if the `href` is present on the element, and not the `rel`.  

Again, per the purposes of _this_ specification, it's largely irrelevant because it doesn't change the fact that, even if exposed developers should not use ARIA on `link` elements.

However, for the purposes of HTML AAM, the mappings are presently inaccurate as the element _does_ have a mapping, even though its default state is for it to not be exposed to the accessibility api.

**Comment by JAWS-test** [comment]
The question is whether we follow the HTML specification or what browsers are currently doing:
* The HTML specification says: certain rel values lead to [external resource links](https://html.spec.whatwg.org/multipage/links.html#external-resource-link) (which are not role=link links) and other rel values lead to hyperlinks. Hyperlinks actually lead to role=link, but not here because they are metadata content.
* My Chrome under Windows 10 for example always shows the link element as "GenericContainer", no matter if with or without href and no matter which value is in rel. In Chrome and IE 11, the element is not displayed as a link and cannot be operated with either the mouse or the keyboard.
* In Firefox it is recognized as a link and can also be operated in this way.

I would suggest that at https://w3c.github.io/html-aria/#el-link instead of "role=link" the following is entered: "No corresponding role".

**Comment by scottaohara** [comment]
(unintentionally) many hours later...

MSAA/AXAPI both map the element to a link (though MSAA may well just be noting the element's name)

IA2 & UIA does not expose a link mapping at the platform level.  but as you noted, Firefox _does_ allow it to be activated like a link.  

Safari will both announce and treat an exposed `link` as a link.

So it's chromium based browsers that will not treat an exposed `link` as anything but a text node. 

Firefox will allow an exposed `link` to be activated as if it were an `a href`, but may not expose it with a `link` role.

Safari will treat an exposed `link` as if it was an `<a href="...">`.

so we are a bit split here, and honestly I can go either way at this point.

I tend to think it's better to provide a mapping for an element which _may_ (even though the chance of this happening is largely confined to this issue thread) have the opportunity to be exposed to users, even if that mapping is not regularly exposed to the accessibility api.  However, this doesn't match the behavior of an exposed `link` in Chromium browsers. 

The counter argument is to not map it at all, (no corresponding role) and rather file bugs against browsers (safari, firefox) to negate functionality for something that should thus not act as a link... but again, also should rarely ever be exposed to users...so... 

@carmacleod, @stevefaulkner do you have an opinion on which way this should go?  Again... this is a rather twisted issue as it may impact ARIA in HTML, HTML AAM, both or neither :)

**Comment by carmacleod** [comment]
No opinion. I've only ever used link for "pulling things in" - never for anything UI. (Wouldn't want to, because who knows what would happen. ;)

Happy to go with whatever @stevefaulkner decides. :)
