### ISSUE TITLE
Redundant conditions in Document Conformance table

### ISSUE THREAD

**Issue by AlexLloyd0** [w3c/html-aria#239]
The document conformance table states that a

> li element whose parent is an ol, ul or menu

has a `role=listitem`.

However `li` *must* be in a `ol`, `ul` or `menu` ([HTML Standard](https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element)) so the condition on parenthood just excludes things like `<ul><div><li>`, but it's not clear to me why that `li` shouldn't have `role=listitem`.

Should that cell of the table just be replaced with `li`?

**Comment by AlexLloyd0** [comment]
Similarly for `td`:

> role=cell if a descendant of a table element.

but I don't think a `td` without a `table` ancestor is valid HTML

**Comment by scottaohara** [comment]
Yeh, that can be simplified to just say `li`.

Webkit/Chromium do still expose a listitem role if a `li` isn't within a list container.  Firefox doesn't.  It just treats it as a text node, which, imo is more accurate there's no parent listing... but 


Regarding `td` though, if a child of a `table role=grid` that cell will become a `role=gridcell`.  so that can stay / will have more clarity once #196 is merged after another review.
