### ISSUE TITLE
Allow gridcell and treeitem roles on button elements

### ISSUE THREAD

**Issue by smhigley** [w3c/html-aria#298]
In the [Rules of ARIA attribute usage by HTML element ](https://w3c.github.io/html-aria/#docconformance), `<button>` already allows every child role of [composite widgets that manage focus](https://w3c.github.io/aria/#managingfocus_authors) except for tree and grid.

There are benefits in using `<button>` as a base of interaction in these widgets, such as:
- Enter/space triggers the click event
- Certain colors and interaction styles are applied automatically in forced color modes like Windows High Contrast Mode.

Those benefits also apply to `gridcell`s and `treeitem`s, so it seems like it would be valuable to add those as well.

Happy to do a PR for this :)

**Comment by scottaohara** [comment]
Closing.  Reasoning provided in the closed PR  #299

**Comment by smhigley** [comment]
@scottaohara would you mind reopening, since we discussed taking a look at this again?

**Comment by scottaohara** [comment]
re: discussion mentioned above - the reason this was re-opened is because while HTML's content model will still disallow nested interactive elements within a button element (regardless if its role was overwritten or not), in further testing there does not appear to be any negative impact from a UX pov.  Additionally, even in situations where using a base button element for these roles, or if one were to include nested interactive elements - any problems found would either be issues for all users (e.g., pressing a gridcell submits a form unexpectedly) or would likely be found via other wcag related testing (automated or manual).
