### ISSUE TITLE
Implicit ARIA semantics for summary should not be "button"

### ISSUE THREAD

**Issue by JAWS-test** [w3c/html-aria#355]
In the column "Implicit ARIA semantics", summary has "button", but summary has no implicit ARIA semantics

See: https://www.w3.org/TR/html-aam-1.0/#summary-element, https://github.com/whatwg/html/issues/2272, https://github.com/w3c/html-aam/issues/345

**Comment by scottaohara** [comment]
adding a blocked label here, because yes HTML AAM does not define `summary` as `role=button`.  However, in almost all implementations this element IS exposed as a `button`... so indicating this in *this specification* isn't really inaccurate either.  

I do think we could add a note to this, stating this particular implicit role matches present reality... but i do not think it solves anything to completely remove the mention of the button role, since anyone could very easily inspect the element or use a screen reader to interact with it and hear this role (again, in almost every implementation).
