### ISSUE TITLE
input[type=file] default role be button?

### ISSUE THREAD

**Issue by jongund** [w3c/html-aria#421]
It seems browsers render a button by default for input[type=file], shouldn't the default role be button?

**Comment by scottaohara** [comment]
this wasn't always the case.  For instance, IE11 used to render a button with a text field.  

Even now, it's not entirely accurate to say this is just a role=button, as while the implementations have become more unified there is generally still a containing element that then houses a button and then a text leaf of the current upload status.  

I'm going to close this issue, but create a new one in HTML AAM as the mappings over there should probably be updated and - judging by the chromium implementation - there are probably things that need to be fixed in that browser.
