### ISSUE TITLE
Form element only gets the form role if it has an accessible name, similar to section element

### ISSUE THREAD

**Issue by jongund** [w3c/html-aria#423]
The current spec says that the `form` element maps by default to the `form` role and the `form` role in the ARIA 1.2 spec says that the `form` role is required to have an accessible name.  I don't think we want accessible names on every `form` element.  Something has to change, seems the easy change is to make the `form` role conditional on the presence of an accessible name, similar to the wording for the `section` element.

**Comment by scottaohara** [comment]
Aria 1.3 adds more clarity here. And html aam is already updated to indicate that a form landmark needs a name, but unnamed the form role may still be exposed, but not as a landmark

since aria in html doesn’t define what roles each element has, any necessary change wouldn’t start here. 

Maybe further clarification is needed in aria.

**Comment by scottaohara** [comment]
closing this issue as this is not the spec that would need a change.

I have filed an issue in ARIA per the necessary further clarification, as the mappings in HTML AAM and Core AAM are also up to date.
