### ISSUE TITLE
Implicit role of "Row" on tr element inconsistent with HTML5 specification

### ISSUE THREAD

**Issue by SiTaggart** [w3c/html-aria#47]
More of a question of which one should I trust. 

[Here I'm told](https://www.w3.org/TR/html-aria/#tr) the `tr` element has an implicit role of `row` and should not set the role. 

[In the HTML5.1 spec](https://www.w3.org/TR/html5/tabular-data.html#the-tr-element) there is no mention of the implicit role (do not apply) on the `tr` element, implying I _should_ add it to a `tr` in a `grid` widget.

This is causing confusion with testing tools like aXe core, which throws a critical error when `role="row"` is missing on a `tr` element.

Which is right?

**Comment by dylanb** [comment]
No, I think what that table says is that you can set ANY role on a `<tr>` element, however your other issue (referenced) is a bug that we need to fix

**Comment by stevefaulkner** [comment]
@SiTaggart @dylanb 
as TR has an implicit role of row, in general it does not need to be set and it is not recommended it be set. Thus it says in the ARIA in HTML spec "Implicit ARIA semantics - SHOULD NOT be used" this is a [normative statement](https://w3c.github.io/html-aria/#conformance-requirements). If you do use it, and check your conformance using the HTMl validator you will get a warning, its a warning (not an error) because there may be some circumstance that merits using it.

@SiTaggart in regards to your question: "Which is right?".
the authoritative spec in this case is ARIA in HTML 
from the [HTML 5.1 spec](https://www.w3.org/TR/html/dom.html#aria-conformance-requirements):

> 3.2.7.2. Conformance Checker Implementation Requirements
> Conformance checkers are required to implement document conformance requirements for use of the ARIA role and aria-\* attributes on HTML elements , as defined in ARIA in HTML. [html-aria]

 The information for use of ARIA provided in the head section of each element definition is informative only. The issue you found with TR is a bug and needs to be fixed in the html spec.

**Comment by stevefaulkner** [comment]
updated informative content in HTML 5.2 for [tr element](https://w3c.github.io/html/tabular-data.html#the-tr-element) to reflect ARIA in HTML

**Comment by SiTaggart** [comment]
Excellent, thanks 👍
