### ISSUE TITLE
Make gridcell one of the implicit roles for the td element

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/html-aria#60]
The spec currently specifies `cell` as the implicit role for `td`. Add `gridcell` as another implicit role for it.

The `th` element has both `columnheader` and `rowheader` as its implicit roles, so from that I glean it’s possible for `td` and other elements to also have multiple implicit roles.

**Comment by dylanb** [comment]
@sideshowbarker `gridcell` inherits from `cell`, so is by definition already a `cell` so the question is not whether it should be both, but rather: should it be `gridcell` instead of `cell`?

The reason is that if it is a `gridcell` it is automatically already a `cell`.

I vote that it should imply `gridcell` because that allows the relationship attributes to be applied along with the implicit semantics.

Alternatively: should the implied semantics change depending on the parent i.e. if a table is changed to `grid` from `table` by applying `role="grid"`, does this mean that the implicit role of `td` changes from `cell` to `gridcell`?

**Comment by asurkov** [comment]
Semantics of course depends on number of things, one of them is a context. I'm not sure however what ARIA specs says about role=grid + HTML:td combination, whether it implies 'gridcell' role on HTML:td element. If it does, then gridcell should be a implicit role for HTML:td if it's part of role='grid' widget.

**Comment by stevefaulkner** [comment]
The question, i think is, does doing `<table role="grid">` cause child `<td>` elements to be exposed with a `gridcell` role? From a quick test https://codepen.io/stevef/pen/OmVeJL with latest chrome and firefox, the answer appears to be no.

**Comment by dylanb** [comment]
@stevefaulkner are you saying that is a bug?

**Comment by mcking65** [comment]
stevefaulkner commented: 

> The question, i think is, does doing `<table role="grid">` cause child `<td>` elements to be exposed with a  gridcell  role? From a quick test 
> https://codepen.io/stevef/pen/OmVeJL
> with latest chrome and firefox, the answer appears to be no.

This should be a browser bug. 

The mapping spec should be as described by @asurkov. That is:
* `td` in a grid should be a gridcell.
* There should be some reasonable defaults for mapping `th` to rowheader or colheader, e.g., row 1 for colheader, col 1/row2+ for `rowheader` in LTR languages.
* Where ambiguous, `th` should map to gridcell.

I believe it should be this way because the spec says in 
[section 7.4 Implicit WAI-ARIA Semantics](http://w3c.github.io/aria/aria/aria.html#implicit_semantics) 
that:

> These host language features can be viewed as having "implicit WAI-ARIA semantics". 
> User agent processing of features with implicit WAI-ARIA semantics would be similar to the processing for the WAI-ARIA feature. 
> The processing might not be identical because of lexical differences between the host language feature and the WAI-ARIA feature, but generally the user agent would expose the same information to the accessibility API. 
> Features with implicit WAI-ARIA semantics satisfy WAI-ARIA structural requirements such as required owned elements, required states and properties, etc. and do not require explicit WAI-ARIA semantics to be provided. 

Mapping a `td` to `cell` when the context is `grid` does not satisfy either required owned elements requirements for grid or the required context role requirements for cell.

**Comment by stevefaulkner** [comment]
I don't actually think it is a bug, after looking at the [ARIA implementation spec for gridcell](http://w3c.github.io/aria/core-aam/core-aam.html#role-map-gridcell) there is no requirement for browsers to expose the `gridcell` role as such, when the `gridcell` role is used it has same  mapping for MSAA + IAccessible2 , AX API, ATK/AT-SPI Role as [cell](http://w3c.github.io/aria/core-aam/core-aam.html#role-map-cell), the UIA Control Type mapping differs though. I also noted that the [ARIA 1.1 grid demos](https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html) don't have `gridcell` on `td`'s

**Comment by dylanb** [comment]
@stevefaulkner is that a bug in the implementation spec then?

**Comment by stevefaulkner** [comment]
> is that a bug in the implementation spec then?

I don't think so as what is in the spec is usually what has been agreed to and implemented by browsers

**Comment by dylanb** [comment]
:-) maybe I should be more explicit.

I think the spec should change because otherwise, even if you are using table markup for a grid, you need to explicitly add all the roles for all the cells which balloons the markup unnecessarily.

**Comment by stevefaulkner** [comment]
> I think the spec should change because otherwise, even if you are using table markup for a grid, you need to explicitly add all the roles for all the cells which balloons the markup unnecessarily.

Ok, so there needs to be an issue filed on the implementation spec, closing this for now.
